{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.parvis",
    "module": "parvis-graph",
    "version": "1.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parvis-graph-1.6.3.jar",
          "url": "parvis-graph-1.6.3.jar",
          "size": 7180599,
          "sha512": "9c69cfaf4de40c830326947c6c8c4d8808c1bde7e3b3f84b12bc3983b0cd446c32bed9a74ddbe5159aa85ddd1802569cd8b619fa5c959a804d7eda5d599b547d",
          "sha256": "2d933bc0e57a0353db306c9168a3b3f88d7581d503b36d706a1e6898673c087c",
          "sha1": "b3ad61dc2b630a00c413aeefb5d4dae04140963a",
          "md5": "d60b2b47071e12e96ec70c25efd31e13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ParVis",
          "module": "base",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "parvis-graph-1.6.3.jar",
          "url": "parvis-graph-1.6.3.jar",
          "size": 7180599,
          "sha512": "9c69cfaf4de40c830326947c6c8c4d8808c1bde7e3b3f84b12bc3983b0cd446c32bed9a74ddbe5159aa85ddd1802569cd8b619fa5c959a804d7eda5d599b547d",
          "sha256": "2d933bc0e57a0353db306c9168a3b3f88d7581d503b36d706a1e6898673c087c",
          "sha1": "b3ad61dc2b630a00c413aeefb5d4dae04140963a",
          "md5": "d60b2b47071e12e96ec70c25efd31e13"
        }
      ]
    }
  ]
}
