{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.parvis",
    "module": "parvis-graph",
    "version": "1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parvis-graph-1.6.jar",
          "url": "parvis-graph-1.6.jar",
          "size": 7180644,
          "sha512": "323c0fe6137febc29ef331a6a6a480729d7908e615c5868f2be5031a35694c7fd961896eb19c670f090c2933fae0dd9d137b675715276e4bedc8c4ff0b1272be",
          "sha256": "f85c0dc7876b02467e0d363319107c6cce978f9928f121efbc368c92bb46efee",
          "sha1": "8ea0ba9f1cf58894111471ce3344f46132f45493",
          "md5": "3eba525ba0c58a100e49b2669efdcc06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ParVis",
          "module": "base",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "parvis-graph-1.6.jar",
          "url": "parvis-graph-1.6.jar",
          "size": 7180644,
          "sha512": "323c0fe6137febc29ef331a6a6a480729d7908e615c5868f2be5031a35694c7fd961896eb19c670f090c2933fae0dd9d137b675715276e4bedc8c4ff0b1272be",
          "sha256": "f85c0dc7876b02467e0d363319107c6cce978f9928f121efbc368c92bb46efee",
          "sha1": "8ea0ba9f1cf58894111471ce3344f46132f45493",
          "md5": "3eba525ba0c58a100e49b2669efdcc06"
        }
      ]
    }
  ]
}
