{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.parvis",
    "module": "parvis-graph",
    "version": "1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parvis-graph-1.6.jar",
          "url": "parvis-graph-1.6.jar",
          "size": 7180037,
          "sha512": "7de685bc4bd0b1bb3858350f2a0ef9ad02c51ccb8edbfbf6e25960b57548fb446740e471fa94938ea821737be579849559c2872ce2c1b266115e1e541a3737ec",
          "sha256": "dc0651c1c04f4fde1a7605ed9d6f937c856f405b5291089ab35b047210aa16db",
          "sha1": "a789c48b61b6e6c4ee595ad52d294378c9b9bc93",
          "md5": "c46501e4ecbbab310ca263b53c5c380e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ParVis",
          "module": "base",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "parvis-graph-1.6.jar",
          "url": "parvis-graph-1.6.jar",
          "size": 7180037,
          "sha512": "7de685bc4bd0b1bb3858350f2a0ef9ad02c51ccb8edbfbf6e25960b57548fb446740e471fa94938ea821737be579849559c2872ce2c1b266115e1e541a3737ec",
          "sha256": "dc0651c1c04f4fde1a7605ed9d6f937c856f405b5291089ab35b047210aa16db",
          "sha1": "a789c48b61b6e6c4ee595ad52d294378c9b9bc93",
          "md5": "c46501e4ecbbab310ca263b53c5c380e"
        }
      ]
    }
  ]
}
