{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.parvis",
    "module": "parvis-graph",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parvis-graph-1.6.1.jar",
          "url": "parvis-graph-1.6.1.jar",
          "size": 7180037,
          "sha512": "53bf33725f9db6f671c007ca0446d598aa89dbf561a38132a7fbe178e25a81f76e1556c72345e1a6de3589315abcd37fcfd970ed722f8a43cef621ad7603d337",
          "sha256": "5e947cfd24b0569a5c1da72371e8cc62ff69f0fef880a1b3a68afd077e3d907a",
          "sha1": "37ba870a855a65243b0c03555c47a20da3d863ca",
          "md5": "f547144a65a2d0e469394968d8855636"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ParVis",
          "module": "base",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "parvis-graph-1.6.1.jar",
          "url": "parvis-graph-1.6.1.jar",
          "size": 7180037,
          "sha512": "53bf33725f9db6f671c007ca0446d598aa89dbf561a38132a7fbe178e25a81f76e1556c72345e1a6de3589315abcd37fcfd970ed722f8a43cef621ad7603d337",
          "sha256": "5e947cfd24b0569a5c1da72371e8cc62ff69f0fef880a1b3a68afd077e3d907a",
          "sha1": "37ba870a855a65243b0c03555c47a20da3d863ca",
          "md5": "f547144a65a2d0e469394968d8855636"
        }
      ]
    }
  ]
}
