{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.parvis",
    "module": "parvis-graph",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parvis-graph-1.6.1.jar",
          "url": "parvis-graph-1.6.1.jar",
          "size": 7180653,
          "sha512": "d3154f0a79cbf7204310dc08bddae6db6a4d9f2c2377ed249cc15277e4563af1655439321507cba4915a7236e679d0553908472e5d77bc393bb2a22750c20e78",
          "sha256": "59198575224a4707ab868345b5374e12e1d0762ce49c51c8b7a2527e71e771dd",
          "sha1": "485a8401a4d709b1b1b84774612d19d07cfe9d74",
          "md5": "aa5516cb61dec3d12acd07b632aa7fb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ParVis",
          "module": "base",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "parvis-graph-1.6.1.jar",
          "url": "parvis-graph-1.6.1.jar",
          "size": 7180653,
          "sha512": "d3154f0a79cbf7204310dc08bddae6db6a4d9f2c2377ed249cc15277e4563af1655439321507cba4915a7236e679d0553908472e5d77bc393bb2a22750c20e78",
          "sha256": "59198575224a4707ab868345b5374e12e1d0762ce49c51c8b7a2527e71e771dd",
          "sha1": "485a8401a4d709b1b1b84774612d19d07cfe9d74",
          "md5": "aa5516cb61dec3d12acd07b632aa7fb4"
        }
      ]
    }
  ]
}
