{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.parvis",
    "module": "parvis-graph",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "fpyqmveyhngq7dinfl3tsaebny"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parvis-graph-1.3.jar",
          "url": "parvis-graph-1.3.jar",
          "size": 6650887,
          "sha512": "b35592b34c27d11fdd4c8434c4022405736eea47a1d061a6df3770f35da9cae7a82455a1ad053da7e07008f7ce3fc81734ffb0218c05774ff0878b521e7a6eb7",
          "sha256": "eaeba86a2fabb827c1f40d17c52b1a32c32d0d123aed804023c4e8799ae9dd05",
          "sha1": "9aca2e01bb599e3f4cb5adf7a9bfe432cf52065b",
          "md5": "fb472c7cd85de433b08726d582f3a4c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ParVis",
          "module": "base",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "javax.activation",
          "module": "javax.activation-api",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "parvis-graph-1.3.jar",
          "url": "parvis-graph-1.3.jar",
          "size": 6650887,
          "sha512": "b35592b34c27d11fdd4c8434c4022405736eea47a1d061a6df3770f35da9cae7a82455a1ad053da7e07008f7ce3fc81734ffb0218c05774ff0878b521e7a6eb7",
          "sha256": "eaeba86a2fabb827c1f40d17c52b1a32c32d0d123aed804023c4e8799ae9dd05",
          "sha1": "9aca2e01bb599e3f4cb5adf7a9bfe432cf52065b",
          "md5": "fb472c7cd85de433b08726d582f3a4c8"
        }
      ]
    }
  ]
}
