{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.parvis",
    "module": "parvis-graph",
    "version": "1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "36czit3lsnee3lqbjsdnksh3zy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parvis-graph-1.5.jar",
          "url": "parvis-graph-1.5.jar",
          "size": 7180595,
          "sha512": "fff32a66497317ada9a2a6d5a9722b43e76331588d84f3a04f3a86490571925d8fb4091d000c11bc0c61fa67e7c4e709411b0022d6b201e2c7f25c4cd1884c0d",
          "sha256": "2c4a80a90d7e412c019a479ff7ceb9cbd06676455d11ca03c9ab31e54a12a399",
          "sha1": "8aa35151faa2b98a352f0af8a0fa8fb42de9997b",
          "md5": "b89d78b7ea5270e498840f0beb1531e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ParVis",
          "module": "base",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "javax.activation",
          "module": "javax.activation-api",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "parvis-graph-1.5.jar",
          "url": "parvis-graph-1.5.jar",
          "size": 7180595,
          "sha512": "fff32a66497317ada9a2a6d5a9722b43e76331588d84f3a04f3a86490571925d8fb4091d000c11bc0c61fa67e7c4e709411b0022d6b201e2c7f25c4cd1884c0d",
          "sha256": "2c4a80a90d7e412c019a479ff7ceb9cbd06676455d11ca03c9ab31e54a12a399",
          "sha1": "8aa35151faa2b98a352f0af8a0fa8fb42de9997b",
          "md5": "b89d78b7ea5270e498840f0beb1531e4"
        }
      ]
    }
  ]
}
