{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2",
    "module": "pp-annotations",
    "version": "0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pp-annotations-0.1-SNAPSHOT.jar",
          "url": "pp-annotations-0.1-SNAPSHOT.jar",
          "size": 8722,
          "sha512": "490adab3271f054a924f976a2c413d8a8d1c683a30189532b529160f75a8b06caed02ef02323b80fb82ad87ec0912d45e494dc820bc5ac91280da5f38b02938d",
          "sha256": "cd7c19ddb3fa4ef8fd55be9433ac4948db873fb8e7cc1e49fefbbc588f39e279",
          "sha1": "c71f8d29aba2b0d958aad3de667f631e92df2644",
          "md5": "db7761744d8d83bed23995af03e950d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pp-annotations-0.1-SNAPSHOT.jar",
          "url": "pp-annotations-0.1-SNAPSHOT.jar",
          "size": 8722,
          "sha512": "490adab3271f054a924f976a2c413d8a8d1c683a30189532b529160f75a8b06caed02ef02323b80fb82ad87ec0912d45e494dc820bc5ac91280da5f38b02938d",
          "sha256": "cd7c19ddb3fa4ef8fd55be9433ac4948db873fb8e7cc1e49fefbbc588f39e279",
          "sha1": "c71f8d29aba2b0d958aad3de667f631e92df2644",
          "md5": "db7761744d8d83bed23995af03e950d2"
        }
      ]
    }
  ]
}
