{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.parvis",
    "module": "parvis-graph",
    "version": "1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "qrwvlddcxvgo3oxtirgdxbwkn4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parvis-graph-1.4.jar",
          "url": "parvis-graph-1.4.jar",
          "size": 6650906,
          "sha512": "dc4844415d5e4b7afd7c52562866683f55d254099a3df9f94856b6941d3eac3a86d57c35afe05f53e261225a75dd2bdc71f25f8de481cc6c8aec88642d05fec8",
          "sha256": "7d5041e8c0388cac2c3155c9040fedf3b13fea1fb70035f1a88d7b8e5901af9a",
          "sha1": "44eb7ae164d1d7b9b0b4074c6c85565d0dff63c6",
          "md5": "42def05e302e0e2313ee8bb7907cffba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ParVis",
          "module": "base",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "javax.activation",
          "module": "javax.activation-api",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "parvis-graph-1.4.jar",
          "url": "parvis-graph-1.4.jar",
          "size": 6650906,
          "sha512": "dc4844415d5e4b7afd7c52562866683f55d254099a3df9f94856b6941d3eac3a86d57c35afe05f53e261225a75dd2bdc71f25f8de481cc6c8aec88642d05fec8",
          "sha256": "7d5041e8c0388cac2c3155c9040fedf3b13fea1fb70035f1a88d7b8e5901af9a",
          "sha1": "44eb7ae164d1d7b9b0b4074c6c85565d0dff63c6",
          "md5": "42def05e302e0e2313ee8bb7907cffba"
        }
      ]
    }
  ]
}
